# -*- coding: utf-8 -*-
"""inference_cnn_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPUqy4pPlCo3DG2h3aDvtMMsoeQShwQ2
"""

import torch
import torch.nn as nn
import torchvision.transforms as transforms
import librosa
import numpy as np
from PIL import Image
import io
import matplotlib.pyplot as plt

# ==============================================================================
# 1. 모델 구조 정의 (SpeechAnxietyCNN Large, Dropout 0.5)
# ==============================================================================
class SpeechAnxietyCNN(nn.Module):
    def __init__(self, dropout=0.5, size='large'):
        super(SpeechAnxietyCNN, self).__init__()

        sizes = {
            'small':  [32, 64, 128],
            'medium': [64, 128, 256],
            'large':  [128, 256, 512]
        }
        filters = sizes[size]

        self.features = nn.Sequential(
            nn.Conv2d(3, filters[0], kernel_size=3, padding=1),
            nn.BatchNorm2d(filters[0]),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(filters[0], filters[1], kernel_size=3, padding=1),
            nn.BatchNorm2d(filters[1]),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),

            nn.Conv2d(filters[1], filters[2], kernel_size=3, padding=1),
            nn.BatchNorm2d(filters[2]),
            nn.ReLU(),
            nn.MaxPool2d(2, 2),
        )

        self.gap = nn.AdaptiveAvgPool2d(1)

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(filters[2], 256),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(256, 3)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.gap(x)
        x = self.classifier(x)
        return x

# ==============================================================================
# 2. 학습된 가중치 로드
# ==============================================================================
model = SpeechAnxietyCNN(dropout=0.5, size='large')
model.load_state_dict(torch.load('best_size_large.pth', map_location='cpu'))
model.eval()

# ==============================================================================
# 3. 멜-스펙트로그램 변환 설정
# ==============================================================================
TARGET_SR = 22050
N_MELS = 128
N_FFT = 2048
HOP_LENGTH = 512
F_MIN = 300
F_MAX = 2500
IMG_SIZE = 224

# 슬라이딩 윈도우 설정
# 근거: 학습 데이터가 3초 단위 조각으로 구성됨
# stride 1.0초: 추론 속도와 정확도의 균형을 고려한 값
#               (3초 윈도우 기준 67% 겹침)
WINDOW_SEC = 3.0
STRIDE_SEC = 1.0

def audio_chunk_to_melspectrogram(y_chunk, sr):
    """
    3초 분량의 오디오 조각을 멜-스펙트로그램 이미지로 변환합니다.
    """
    mel_spec = librosa.feature.melspectrogram(
        y=y_chunk,
        sr=sr,
        n_mels=N_MELS,
        n_fft=N_FFT,
        hop_length=HOP_LENGTH,
        fmin=F_MIN,
        fmax=F_MAX
    )
    mel_spec_db = librosa.power_to_db(mel_spec, ref=np.max)

    fig, ax = plt.subplots(figsize=(2.24, 2.24), dpi=100)
    ax.set_position([0, 0, 1, 1])
    librosa.display.specshow(mel_spec_db, sr=sr, hop_length=HOP_LENGTH,
                              fmin=F_MIN, fmax=F_MAX, cmap='magma', ax=ax)
    ax.axis('off')

    buf = io.BytesIO()
    plt.savefig(buf, format='png', bbox_inches='tight', pad_inches=0)
    plt.close()
    buf.seek(0)

    img = Image.open(buf).convert('RGB')
    return img

# ==============================================================================
# 4. 이미지 전처리
# ==============================================================================
transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5],
                        std=[0.5, 0.5, 0.5])
])

# ==============================================================================
# 5. 추론 함수 (wav 파일 입력, 슬라이딩 윈도우 적용)
# ==============================================================================
THRESHOLDS = {
    'prolongation': 0.4,
    'tremor': 0.3,
    'energy': 0.3,
}

def predict(audio_path):
    """
    wav 파일을 입력받아 발화 불안도 확률값과 점수를 반환합니다.

    처리 흐름:
    1. 전체 음성을 로드
    2. 3초 길이보다 짧으면 반사 패딩(reflect)으로 3초로 보정
       (학습 데이터 전처리 방식과 동일)
    3. 3초 윈도우, 1초 stride로 슬라이딩하며 각 조각을
       멜-스펙트로그램으로 변환 후 CNN 추론
    4. 모든 윈도우의 확률값을 평균내어 최종 결과 산출

    근거:
    학습 데이터가 3초 단위 조각으로 구성되어 있어
    전체 음성을 그대로 입력하면 시간축이 압축/왜곡되어
    학습 시 보지 못한 입력 형태가 됩니다.
    따라서 학습 때와 동일한 3초 단위로 잘라 추론하며,
    1초 stride는 추론 속도와 정확도의 균형을 고려한 값입니다.

    Args:
        audio_path: wav 파일 경로

    Returns:
        dict: 확률값 및 점수
            - prolongation, tremor, energy: 평균 확률값
            - prolongation_score, tremor_score, energy_score: 점수 (0~100)
            - window_count: 추론에 사용된 윈도우 개수
    """
    y, sr = librosa.load(audio_path, sr=TARGET_SR)

    window_len = int(WINDOW_SEC * sr)
    stride_len = int(STRIDE_SEC * sr)

    # 3초보다 짧으면 반사 패딩으로 3초 보정
    if len(y) < window_len:
        pad_len = window_len - len(y)
        y = np.pad(y, (0, pad_len), mode='reflect')

    # 슬라이딩 윈도우로 자르기
    chunks = []
    start = 0
    while start + window_len <= len(y):
        chunks.append(y[start:start + window_len])
        start += stride_len

    # 마지막 구간이 누락되는 경우, 끝부분 3초를 추가로 포함
    if not chunks or (len(y) - (len(chunks) - 1) * stride_len) > stride_len:
        chunks.append(y[-window_len:])

    # 각 윈도우별 추론
    all_probs = []
    for chunk in chunks:
        img = audio_chunk_to_melspectrogram(chunk, sr)
        img_tensor = transform(img).unsqueeze(0)

        with torch.no_grad():
            output = model(img_tensor)
            probs = torch.sigmoid(output)

        all_probs.append(probs.squeeze(0).numpy())

    # 전체 윈도우 평균
    avg_probs = np.mean(all_probs, axis=0)

    result = {
        'prolongation': round(float(avg_probs[0]), 4),
        'tremor':       round(float(avg_probs[1]), 4),
        'energy':       round(float(avg_probs[2]), 4)
    }

    scores = {
        'prolongation_score': round(100 * (1 - result['prolongation']), 1),
        'tremor_score':       round(100 * (1 - result['tremor']), 1),
        'energy_score':       round(100 * (1 - result['energy']), 1)
    }

    return {**result, **scores, 'window_count': len(chunks)}

# ==============================================================================
# 6. 사용 예시
# ==============================================================================
if __name__ == "__main__":
    audio_path = "test.wav"
    result = predict(audio_path)
    print(f"분석에 사용된 윈도우 수: {result['window_count']}개\n")
    print("확률값:")
    print(f"  prolongation: {result['prolongation']}")
    print(f"  tremor:       {result['tremor']}")
    print(f"  energy:       {result['energy']}")
    print("\n점수:")
    print(f"  연장 제어력:   {result['prolongation_score']}점")
    print(f"  떨림 제어력:   {result['tremor_score']}점")
    print(f"  에너지 안정도: {result['energy_score']}점")