# -*- coding: utf-8 -*-
"""analyze_filler_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0TvrkN__gj17pAq5d5Oaf_gYUzpHVL5
"""

import os
import librosa
import whisper

# ==============================================================================
# 채움말(filler) 분석 함수 - librosa + Whisper 결합 방식
# ==============================================================================

# 채움말 소리로 판단할 구간 길이 범위 (초)
# "어", "음" 같은 짧은 비언어적 발화의 일반적인 길이
FILLER_MIN_DURATION = 0.1
FILLER_MAX_DURATION = 0.8

def analyze_filler(audio_path):
    """
    발화 중 채움말을 분석하여 점수를 반환합니다.

    배경:
    Whisper STT는 "어", "음" 같은 비언어적 발화(filled pause)를
    텍스트 변환 과정에서 생략하거나 인접 단어에 흡수시키는
    경향이 있습니다. 이를 보완하기 위해 librosa로 탐지한
    전체 소리 구간 중 Whisper가 단어로 인식하지 못한
    짧은 구간을 채움말 후보로 판정합니다.

    처리 흐름:
    1. librosa로 소리 있는 구간 전체 탐지
    2. Whisper로 단어별 timestamp 추출
    3. 소리 구간 중 Whisper 단어와 겹치지 않는
       짧은 구간(0.1~0.8초)을 채움말로 판정
    4. 채움말 비율 기반 점수 환산

    한계:
    - word-level timestamp 정밀도 한계로 인접 발화와의
      경계가 모호한 경우 숨소리, 입소리 등이 오탐될 수 있음
    - 방학 중 음향 에너지 패턴 기반으로 정밀도 개선 예정

    사용 환경 안내:
    - 유튜브 영상 등 배경음악이 있는 경우: Demucs 배경음 제거 후 적용 권장
    - 휴대폰 직접 녹음의 경우: 별도 배경음 제거 없이 바로 사용 가능

    Args:
        audio_path: wav 파일 경로

    Returns:
        dict: 채움말 분석 결과 및 점수
            - total_duration_sec: 전체 발화 시간
            - sound_segment_count: librosa로 탐지한 전체 소리 구간 수
            - filler_count: 채움말로 판정된 구간 수
            - filler_ratio: 채움말 비율 (전체 소리 구간 대비)
            - fluency_score: 오각형 점수 (0~100)
    """
    # --------------------------------------------------------------------
    # 1. librosa로 소리 구간 탐지
    # --------------------------------------------------------------------
    y, sr = librosa.load(audio_path, sr=None)
    total_duration = librosa.get_duration(y=y, sr=sr)

    sound_segments = librosa.effects.split(y, top_db=30)
    sound_segments_sec = [(start / sr, end / sr) for start, end in sound_segments]

    # --------------------------------------------------------------------
    # 2. Whisper로 단어별 timestamp 추출
    # --------------------------------------------------------------------
    model = whisper.load_model("base")
    result = model.transcribe(audio_path, language="ko", word_timestamps=True)

    word_segments = []
    for segment in result["segments"]:
        for word_info in segment.get("words", []):
            word_segments.append((word_info["start"], word_info["end"]))

    # --------------------------------------------------------------------
    # 3. 소리 구간 중 Whisper 단어와 겹치지 않는 짧은 구간 = 채움말 후보
    # --------------------------------------------------------------------
    filler_count = 0

    for seg_start, seg_end in sound_segments_sec:
        seg_duration = seg_end - seg_start

        # 채움말 소리 길이 범위에 해당하는지 확인
        if not (FILLER_MIN_DURATION <= seg_duration <= FILLER_MAX_DURATION):
            continue

        # Whisper 단어 구간과 겹치는지 확인
        overlap_found = False
        for word_start, word_end in word_segments:
            overlap = min(seg_end, word_end) - max(seg_start, word_start)
            if overlap > 0:
                # 소리 구간의 50% 이상이 단어와 겹치면 "단어의 일부"로 판단
                if overlap / seg_duration >= 0.5:
                    overlap_found = True
                    break

        # Whisper 단어와 겹치지 않는 짧은 소리 구간 = 채움말 소리
        if not overlap_found:
            filler_count += 1

    # --------------------------------------------------------------------
    # 4. 점수 환산
    # --------------------------------------------------------------------
    sound_segment_count = len(sound_segments_sec)
    filler_ratio = filler_count / sound_segment_count if sound_segment_count > 0 else 0

    fluency_score = round(100 * (1 - filler_ratio), 1)
    fluency_score = max(0, min(100, fluency_score))

    return {
        "total_duration_sec": round(total_duration, 2),
        "sound_segment_count": sound_segment_count,
        "filler_count": filler_count,
        "filler_ratio": round(filler_ratio, 4),
        "fluency_score": fluency_score
    }


if __name__ == "__main__":
    # 테스트할 wav 파일 경로 입력
    # 유튜브 영상 테스트 시: Demucs 배경음 제거 후 파일 사용 권장
    # 휴대폰 녹음 테스트 시: 바로 사용 가능
    test_path = "test.wav"

    if os.path.exists(test_path):
        result = analyze_filler(test_path)
        print("="*50)
        print("[채움말 분석 결과]")
        print("="*50)
        print(f"전체 발화 시간:    {result['total_duration_sec']}초")
        print(f"전체 소리 구간 수: {result['sound_segment_count']}개")
        print(f"채움말 구간 수:    {result['filler_count']}개")
        print(f"채움말 비율:       {result['filler_ratio']*100}%")
        print(f"발화 유창성 점수:  {result['fluency_score']}점")
    else:
        print("[INFO] 테스트 파일 없음 - 함수 정의만 완료")